const FOOD={鸡腿肉:'🍗',鸡胸肉:'🍗',猪肉:'🥩',牛肉:'🥩',虾仁:'🦐',鱼片:'🐟',香肠:'🌭',培根:'🥓',鸡蛋:'🥚',豆腐:'⬜',番茄:'🍅',土豆:'🥔',包菜:'🥬',白菜:'🥬',青菜:'🥬',菠菜:'🥬',西兰花:'🥦',蘑菇:'🍄',金针菇:'🍄',青椒:'🫑',洋葱:'🧅',胡萝卜:'🥕',黄瓜:'🥒',茄子:'🍆',芹菜:'🥬',豆芽:'🌱',玉米:'🌽',南瓜:'🎃',红薯:'🍠',葱:'🌿',姜:'🫚',蒜:'🧄',大米:'🍚',挂面:'🍜',水饺:'🥟',包子:'🥟',手抓饼:'🫓',面包:'🍞',牛奶:'🥛'};
const SEASON=['食用油','盐','糖','生抽','老抽','料酒','醋','蚝油','淀粉','胡椒','香油','豆瓣酱','番茄酱'];
const TOOLS=['炒锅','平底锅','汤锅','电饭煲','蒸锅','微波炉','空气炸锅','烤箱'];
const R=(id,name,icon,cat,tags,mins,desc,ings,season,tools,steps)=>({id,name,icon,cat,tags,mins,desc,ings,season,tools,steps});
const recipes=[
R('r1','土豆烧鸡','🍲','肉菜',['下饭','一锅'],30,'鸡肉和土豆一起焖，适合配米饭',[['鸡腿肉','300g','切约3cm小块'],['土豆','2个','去皮切滚刀块']],[['食用油','适量',1],['生抽','1.5勺',1],['盐','适量',1],['老抽','半勺',0]],[['炒锅','平底锅']],['锅热加油，下鸡腿肉炒至变色。','加入土豆翻炒1分钟，加入生抽。','加清水至食材一半高度，大火煮开。','转中小火焖至土豆软糯、鸡肉熟透。','开盖收汁，补盐即可。']),
R('r2','包菜炒鸡','🥘','肉菜',['快手','下饭'],15,'鸡肉配包菜，简单快速',[['鸡腿肉','200g','切薄片或小块'],['包菜','半颗','撕小片并沥干']],[['食用油','适量',1],['生抽','1勺',1],['盐','适量',1],['蚝油','半勺',0]],[['炒锅','平底锅']],['锅热加油，下鸡肉炒至变色。','加入包菜大火翻炒。','加生抽和盐。','包菜断生后出锅。']),
R('r3','小鸡炖蘑菇','🍲','汤炖',['暖胃','一锅'],40,'鸡肉和蘑菇慢炖，汤汁浓郁',[['鸡腿肉','300g','切块'],['蘑菇','200g','洗净，大的切半']],[['食用油','少量',1],['盐','适量',1],['生抽','1勺',1],['料酒','1勺',0]],[['汤锅','炒锅']],['少量油把鸡肉炒至微黄。','加入蘑菇炒软。','加入生抽和热水煮开。','小火炖约25分钟。','最后加盐。']),
R('r4','番茄炒蛋','🍳','蛋类',['快手','家常'],10,'酸甜鲜香的家常经典',[['番茄','2个','切块'],['鸡蛋','3个','打散']],[['食用油','适量',1],['盐','适量',1],['糖','少量',0]],[['炒锅','平底锅']],['鸡蛋炒至刚凝固后盛出。','番茄下锅炒软出汁。','加盐，可加少量糖。','倒回鸡蛋翻匀。']),
R('r5','手撕包菜','🥬','素菜',['快手','省事'],8,'脆爽下饭，食材很简单',[['包菜','半颗','撕小片并沥干']],[['食用油','适量',1],['盐','适量',1],['生抽','半勺',0],['醋','少量',0]],[['炒锅','平底锅']],['锅烧热后加油。','放入包菜快速翻炒。','加盐，可加少量生抽。','断生即可。']),
R('r6','清炒土豆丝','🥔','素菜',['快手','家常'],12,'清爽脆口的基础家常菜',[['土豆','2个','切细丝并洗去表面淀粉']],[['食用油','适量',1],['盐','适量',1],['醋','少量',0]],[['炒锅','平底锅']],['锅热加油，下土豆丝。','大火翻炒约2分钟。','加盐继续翻炒。','喜欢酸味可淋醋。']),
R('r7','青椒炒肉','🫑','肉菜',['下饭','快手'],15,'青椒与猪肉的经典搭配',[['猪肉','200g','切薄片'],['青椒','2个','去籽切块或丝']],[['食用油','适量',1],['生抽','1勺',1],['盐','适量',1],['淀粉','少量',0]],[['炒锅','平底锅']],['猪肉炒至变色。','加入青椒大火翻炒。','加入生抽和盐。','青椒断生后出锅。']),
R('r8','青菜面','🍜','主食',['省事','一人食'],12,'一锅就能解决的一顿饭',[['挂面','1人份','按食量取出'],['青菜','1把','洗净']],[['盐','适量',1],['生抽','半勺',0],['胡椒','少量',0]],[['汤锅']],['水烧开，下挂面。','面条接近熟时加入青菜。','加盐调味。','煮好后盛出。']),
R('r9','煮水饺','🥟','速食',['省事','速食'],10,'冷冻水饺也可以直接解决一顿饭',[['水饺','1人份','无需提前解冻']],[],[['汤锅']],['足量水烧开。','下水饺并轻推避免粘底。','再次沸腾后按包装时间煮熟。','捞出即可。']),
R('r10','鸡蛋炒饭','🍚','主食',['快手','清库存'],12,'剩米饭的高效吃法',[['大米','1碗熟米饭','最好冷藏过'],['鸡蛋','2个','打散'],['葱','少量','切葱花']],[['食用油','适量',1],['盐','适量',1],['生抽','少量',0]],[['炒锅','平底锅']],['先炒鸡蛋。','加入米饭炒散。','加盐，可加生抽。','撒葱花翻匀。']),
R('r11','洋葱炒蛋','🧅','蛋类',['快手','家常'],10,'洋葱甜香配鸡蛋',[['洋葱','1个','切丝'],['鸡蛋','3个','打散']],[['食用油','适量',1],['盐','适量',1]],[['炒锅','平底锅']],['鸡蛋炒至半熟盛出。','洋葱炒软。','倒回鸡蛋。','加盐翻匀。']),
R('r12','西兰花炒虾仁','🥦','肉菜',['清淡','快手'],15,'清爽高蛋白搭配',[['西兰花','半颗','切小朵'],['虾仁','200g','擦干水分']],[['食用油','适量',1],['盐','适量',1],['料酒','少量',0]],[['炒锅','平底锅']],['西兰花焯水后沥干。','虾仁炒至变色。','加入西兰花翻炒。','加盐出锅。']),
R('r13','红烧豆腐','⬜','素菜',['下饭','省钱'],18,'豆腐软嫩，酱汁下饭',[['豆腐','1盒','切块'],['葱','少量','切葱花']],[['食用油','适量',1],['生抽','1勺',1],['盐','少量',1],['淀粉','少量',0]],[['炒锅','平底锅']],['豆腐煎至微黄。','加生抽和少量清水。','小火焖5分钟。','撒葱花出锅。']),
R('r14','黄瓜炒蛋','🥒','蛋类',['快手','清淡'],10,'黄瓜清脆，鸡蛋柔软',[['黄瓜','1根','切片'],['鸡蛋','3个','打散']],[['食用油','适量',1],['盐','适量',1]],[['炒锅','平底锅']],['鸡蛋炒熟盛出。','黄瓜快速翻炒。','倒回鸡蛋。','加盐翻匀。']),
R('r15','番茄牛肉汤','🥣','汤炖',['暖胃','一锅'],25,'番茄酸香，牛肉鲜嫩',[['牛肉','200g','切薄片'],['番茄','2个','切块'],['姜','2片','切片']],[['盐','适量',1],['胡椒','少量',0]],[['汤锅']],['番茄煮软出汁。','加入热水和姜片。','下牛肉片煮熟。','加盐调味。']),
R('r16','南瓜粥','🎃','主食',['清淡','早餐'],35,'南瓜甜糯，适合早餐或晚餐',[['南瓜','200g','切小块'],['大米','半杯','淘洗']],[],[['汤锅','电饭煲']],['大米和南瓜一起加水。','煮开后转小火。','煮至米粒开花、南瓜软烂。','按喜好调稠度。']),
R('r17','蒸包子','🥟','速食',['早餐','省事'],12,'冷冻包子直接蒸热即可',[['包子','2个','冷冻可直接蒸']],[],[['蒸锅','电饭煲']],['锅中加水。','放入包子。','水开后蒸约8至10分钟。','关火焖1分钟。']),
R('r18','煎手抓饼','🫓','速食',['早餐','快手'],8,'无需解冻，直接煎到酥脆',[['手抓饼','1张','无需解冻']],[['食用油','少量',0]],[['平底锅']],['平底锅预热。','放入手抓饼。','中小火两面煎金黄。','出锅即可。']),
R('r19','芹菜炒肉','🥬','肉菜',['家常','下饭'],15,'芹菜爽脆，猪肉鲜香',[['猪肉','200g','切丝'],['芹菜','2根','切段']],[['食用油','适量',1],['生抽','1勺',1],['盐','适量',1]],[['炒锅','平底锅']],['猪肉炒至变色。','加入芹菜翻炒。','加生抽和盐。','芹菜断生即可。']),
R('r20','蒜蓉青菜','🥬','素菜',['快手','清淡'],6,'最快解决一把青菜',[['青菜','1把','洗净沥干'],['蒜','2瓣','切末']],[['食用油','适量',1],['盐','适量',1]],[['炒锅','平底锅']],['蒜末炒香。','下青菜大火翻炒。','加盐。','断生立即出锅。']),
R('r21','培根鸡蛋卷饼','🥓','主食',['早餐','快手'],10,'手抓饼加培根鸡蛋就能成一餐',[['手抓饼','1张','无需解冻'],['培根','2片','直接使用'],['鸡蛋','1个','打散或整颗']],[['番茄酱','适量',0]],[['平底锅']],['培根先煎至微卷。','手抓饼煎至一面金黄。','加入鸡蛋并翻面。','放培根卷起。']),
R('r22','金针菇豆腐汤','🍄','汤炖',['省钱','清淡'],15,'金针菇和豆腐的轻汤',[['金针菇','1把','去根洗净'],['豆腐','半盒','切块']],[['盐','适量',1],['胡椒','少量',0],['香油','少量',0]],[['汤锅']],['水烧开后下豆腐。','加入金针菇。','煮约5分钟。','加盐即可。'])
];
const defaults={seasonings:{食用油:1,盐:1,糖:1,生抽:1,老抽:0,料酒:0,醋:1,蚝油:1,淀粉:1,胡椒:0,香油:0,豆瓣酱:0,番茄酱:0},cookware:{炒锅:1,平底锅:1,汤锅:1,电饭煲:1,蒸锅:0,微波炉:1,空气炸锅:0,烤箱:0}};
const clone=x=>JSON.parse(JSON.stringify(x)),uniq=a=>[...new Set(a)],q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function migrate(raw){let o=raw||{},foods=Array.isArray(o.foods)?o.foods:Array.isArray(o.inv)?o.inv.filter(x=>FOOD[x.name]).map(x=>x.name):[];let s={version:'0.1.5',scene:['fridge','board','stove'].includes(o.scene)?o.scene:'board',foods:uniq(foods.filter(x=>FOOD[x])),set:clone(defaults),shopping:Array.isArray(o.shopping)?o.shopping:[],recipe:recipes.some(r=>r.id===o.recipe)?o.recipe:null,prep:null,cook:o.cook&&recipes.some(r=>r.id===o.cook.recipe)?o.cook:null,filter:o.filter||'全部',query:o.query||'',viewMode:o.viewMode==='list'?'list':'cards'};if(o.set){s.set.seasonings={...s.set.seasonings,...(o.set.seasonings||{})};s.set.cookware={...s.set.cookware,...(o.set.cookware||{})}}return s}
let state=migrate(JSON.parse(localStorage.getItem('mk01')||'null'));
function save(){localStorage.setItem('mk01',JSON.stringify(state));let e=q('#shopCount');if(e)e.textContent=state.shopping.length}function close(){q('#modal').innerHTML=''}function toast(t){q('#toast').innerHTML='<div class="toast">'+t+'</div>';setTimeout(()=>q('#toast').innerHTML='',1800)}
const key=(k,n)=>k+':'+n;function inShop(k,n){return state.shopping.some(x=>key(x.kind,x.name)===key(k,n))}function addShop(k,n){if(!inShop(k,n))state.shopping.push({kind:k,name:n})}function rmShop(k,n){state.shopping=state.shopping.filter(x=>key(x.kind,x.name)!==key(k,n))}
function has(k,n){return k==='food'?state.foods.includes(n):k==='seasoning'?!!state.set.seasonings[n]:!!state.set.cookware[n]}function have(k,n){rmShop(k,n);if(k==='food')state.foods=uniq([...state.foods,n]);if(k==='seasoning')state.set.seasonings[n]=1;if(k==='tool')state.set.cookware[n]=1;save()}function missing(k,n){if(k==='food')state.foods=state.foods.filter(x=>x!==n);if(k==='seasoning')state.set.seasonings[n]=0;if(k==='tool')state.set.cookware[n]=0;save()}
const required=r=>[...r.ings.map(x=>['food',x[0],x[1]]),...r.season.filter(x=>x[2]).map(x=>['seasoning',x[0],x[1]])],miss=r=>required(r).filter(x=>!has(x[0],x[1])),toolOK=r=>r.tools.every(g=>g.some(n=>has('tool',n)));
function rs(r){let a=required(r),m=miss(r);return{have:a.length-m.length,total:a.length,missing:m.length,tool:toolOK(r),ready:m.length===0&&toolOK(r)}}function status(r){let s=rs(r),shopping=miss(r).filter(x=>inShop(x[0],x[1])).length;return s.ready?'<span class="tag good">可以准备</span>':shopping?`<span class="tag bad">待买 ${shopping}</span>`:`<span class="tag warn">缺 ${s.missing+(s.tool?0:1)}</span>`}
function go(scene){state.scene=scene;state.prep=null;save();render()}function render(){qa('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.s===state.scene));q('#sub').textContent=state.scene==='board'?(state.prep?'准备食材':'做什么'):state.scene==='fridge'?'有什么':'怎么做';state.scene==='board'?board():state.scene==='fridge'?fridge():stove()}
function board(){if(state.prep)return prepView();let cats=['全部','肉菜','素菜','蛋类','主食','汤炖','速食'],list=recipes.filter(r=>(state.filter==='全部'||r.cat===state.filter)&&(!state.query||r.name.includes(state.query)||r.ings.some(x=>x[0].includes(state.query))||r.tags.some(x=>x.includes(state.query))));let body=state.viewMode==='list'?`<div class="recipe-list">${list.map(r=>`<button class="recipe-row" data-r="${r.id}"><div class="icon">${r.icon}</div><div><h3>${r.name}</h3><p>${r.desc}</p></div><div class="row-meta"><span class="tag">${r.mins}分钟</span>${status(r)}</div></button>`).join('')}</div>`:`<div class="recipe-grid">${list.map(r=>`<button class="recipe-card" data-r="${r.id}"><div class="icon">${r.icon}</div><h3>${r.name}</h3><p>${r.desc}</p><div class="meta"><span class="tag">约${r.mins}分钟</span><span class="tag">${r.cat}</span>${status(r)}</div></button>`).join('')}</div>`;q('#root').innerHTML=`<h2>🔪 菜板</h2><div class="board-tools"><div class="search-row"><input id="search" class="search" placeholder="搜索菜名或食材" value="${state.query}"><div class="view-switch"><button data-view="cards" class="${state.viewMode==='cards'?'on':''}">▦</button><button data-view="list" class="${state.viewMode==='list'?'on':''}">☰</button></div></div><div class="filters">${cats.map(c=>`<button class="filter ${state.filter===c?'on':''}" data-cat="${c}">${c}</button>`).join('')}</div></div>${body||'<div class="empty">没有找到菜谱</div>'}`;q('#search').oninput=e=>{state.query=e.target.value.trim();save();board()};qa('[data-view]').forEach(b=>b.onclick=()=>{state.viewMode=b.dataset.view;save();board()});qa('[data-cat]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.cat;save();board()});qa('[data-r]').forEach(b=>b.onclick=()=>recipeModal(b.dataset.r))}
function needRow(k,n,amt,opt=0){let h=has(k,n),shop=inShop(k,n),icon=k==='food'?(FOOD[n]||'🥣'):'🧂';return`<div class="need ${h?'state-have':shop?'state-shop':''}"><div class="need-icon">${icon}</div><div class="need-info"><strong>${n}${opt?'<span class="optional">可省</span>':''}</strong><small>${amt}</small></div><button class="have-toggle ${h?'on':shop?'shop':''}" data-have="${k}|${n}">${h?'✓ 有':shop?'购物袋':'标为有'}</button></div>`}
function recipeModal(id){let r=recipes.find(x=>x.id===id);if(!r)return;state.recipe=id;save();let s=rs(r),m=miss(r),bad=r.tools.filter(g=>!g.some(n=>has('tool',n))),optional=r.season.filter(x=>!x[2]).length,shopN=m.filter(x=>inShop(x[0],x[1])).length;q('#modal').innerHTML=`<div class="modal"><div class="sheet"><div class="sheet-handle"></div><div class="sheet-head"><div class="title"><b>${r.icon} ${r.name}</b><small>${r.desc} · 约${r.mins}分钟</small></div><button class="icon-close" id="x">×</button></div><div class="recipe-summary"><div class="summary-cell"><b>${s.have}/${s.total}</b><small>必需项已有</small></div><div class="summary-cell"><b>${shopN}</b><small>已在购物袋</small></div><div class="summary-cell"><b>${s.tool?'✓':'—'}</b><small>厨具</small></div></div><div class="section-title">食材 <span class="count">${r.ings.length}项</span></div><div class="need-list">${r.ings.map(x=>needRow('food',x[0],x[1])).join('')}</div><div class="section-title">调味 <span class="count">必需${r.season.filter(x=>x[2]).length}${optional?' · 可省'+optional:''}</span></div><div class="need-list">${r.season.length?r.season.map(x=>needRow('seasoning',x[0],x[1],!x[2])).join(''):'<div class="muted">不需要额外调味料</div>'}</div><div class="section-title">厨具</div>${r.tools.map(g=>{let active=g.find(n=>has('tool',n));return`<div class="tool-need"><div class="tool-head"><div class="need-icon">🍳</div><div><strong>${g.join(' / ')}</strong><small>任选一种即可</small></div><span class="tool-status ${active?'have':''}">${active?'已有 '+active:'还没确认'}</span></div><div class="tool-options">${g.map(n=>`<button class="toolbtn ${has('tool',n)?'on':''}" data-tool="${n}">${has('tool',n)?'✓ ':''}${n}</button>`).join('')}</div></div>`}).join('')}${bad.length?`<div class="blocker">缺厨具：${bad.map(g=>g.join(' / ')+'（任选一种）').join('；')}</div>`:m.length?`<div class="blocker">还缺 ${m.length} 项，可以一次加入购物袋。</div>`:'<div class="ready">✓ 条件齐全，可以开始准备。</div>'}<div class="sheet-footer"><div class="dual"><button class="secondary" id="back">返回菜谱</button><button class="primary" id="act">${m.length?'缺的加入购物袋（'+m.length+'）':bad.length?'先确认厨具':'开始准备'}</button></div></div></div></div>`;q('#x').onclick=close;q('#back').onclick=close;qa('[data-have]').forEach(b=>b.onclick=()=>{let[k,n]=b.dataset.have.split('|');has(k,n)?missing(k,n):have(k,n);recipeModal(id)});qa('[data-tool]').forEach(b=>b.onclick=()=>{let n=b.dataset.tool;has('tool',n)?missing('tool',n):have('tool',n);recipeModal(id)});q('#act').onclick=()=>{let mm=miss(r);if(mm.length){mm.forEach(x=>addShop(x[0],x[1]));save();return shoppingModal(id)}if(!toolOK(r))return toast('请先确认一种可用厨具');state.prep={recipe:id,checked:{}};save();close();render()}}
function prepView(){let r=recipes.find(x=>x.id===state.prep.recipe),done=Object.values(state.prep.checked).filter(Boolean).length;q('#root').innerHTML=`<h2>🔪 准备 · ${r.name}</h2><div class="card"><div class="head"><b>食材准备</b><small>${done}/${r.ings.length}</small></div><div class="prep-list">${r.ings.map(x=>{let ck=!!state.prep.checked[x[0]];return`<div class="prep ${ck?'done':''}"><button class="prep-check" data-p="${x[0]}">${ck?'✓':'○'}</button><div><strong>${FOOD[x[0]]||'🥣'} ${x[0]} · ${x[1]}</strong><small>${x[2]}</small></div></div>`}).join('')}</div><div class="section-title">调味</div><div class="meta">${r.season.map(x=>`<span class="tag ${x[2]?'good':''}">${x[0]} · ${x[1]}${x[2]?'':' · 可省'}</span>`).join('')}</div><div class="dual" style="margin-top:13px"><button class="secondary" id="reselect">重新选菜</button><button class="primary" id="cook">去灶台</button></div></div>`;qa('[data-p]').forEach(b=>b.onclick=()=>{state.prep.checked[b.dataset.p]=!state.prep.checked[b.dataset.p];save();render()});q('#reselect').onclick=()=>{state.prep=null;save();render()};q('#cook').onclick=()=>{if(!rs(r).ready){state.prep=null;save();return recipeModal(r.id)}state.cook={recipe:r.id,step:0};state.prep=null;save();go('stove')}}
function stove(){if(!state.cook){q('#root').innerHTML='<h2>🍳 灶台</h2><div class="card empty">还没有要做的菜。<br><button class="primary" style="margin-top:12px" onclick="go(\'board\')">去菜板选菜</button></div>';return}let r=recipes.find(x=>x.id===state.cook.recipe),i=state.cook.step;q('#root').innerHTML=`<h2>🍳 ${r.name}</h2><div class="preflight">✓ 食材、调味和厨具已确认。</div><div class="card cook"><div class="head"><b>步骤 ${i+1}/${r.steps.length}</b><small>约${r.mins}分钟</small></div><div class="step">${r.steps[i]}</div><div class="pan"></div><div class="actions"><button class="secondary" id="prev">上一步</button><button class="next" id="next">下一步</button><button class="finish" id="done">完成</button></div></div>`;q('#prev').onclick=()=>{state.cook.step=Math.max(0,i-1);save();render()};q('#next').onclick=()=>{state.cook.step=Math.min(r.steps.length-1,i+1);save();render()};q('#done').onclick=()=>{state.cook=null;save();go('board');toast('开饭啦 🎉')}}
function fridge(){q('#root').innerHTML=`<h2>🧊 冰箱</h2><div class="card fridge-section"><div class="head"><b>食材</b><div class="fridge-actions"><small>${state.foods.length} 种</small><button class="mini-add" data-manage="food">＋ 添加</button></div></div>${state.foods.length?`<div class="home-grid">${state.foods.map(n=>`<button class="home-item" data-remove="food|${n}">${FOOD[n]} ${n}</button>`).join('')}</div>`:'<div class="empty">还没有食材</div>'}</div><div class="card fridge-section"><div class="head"><b>调味料</b><button class="mini-add" data-manage="seasoning">＋ 添加</button></div><div class="home-grid">${SEASON.filter(n=>has('seasoning',n)).map(n=>`<button class="home-item" data-remove="seasoning|${n}">🧂 ${n}</button>`).join('')||'<div class="empty">还没有调味料</div>'}</div></div><div class="card fridge-section"><div class="head"><b>厨具</b><button class="mini-add" data-manage="tool">＋ 添加</button></div><div class="home-grid">${TOOLS.filter(n=>has('tool',n)).map(n=>`<button class="home-item" data-remove="tool|${n}">🍳 ${n}</button>`).join('')||'<div class="empty">还没有厨具</div>'}</div></div>`;qa('[data-remove]').forEach(b=>b.onclick=()=>{let[k,n]=b.dataset.remove.split('|');missing(k,n);render()});qa('[data-manage]').forEach(b=>b.onclick=()=>manageModal(b.dataset.manage))}
function manageModal(tab='food'){let names=tab==='food'?Object.keys(FOOD):tab==='seasoning'?SEASON:TOOLS,icon=n=>tab==='food'?FOOD[n]:tab==='seasoning'?'🧂':'🍳';q('#modal').innerHTML=`<div class="modal"><div class="sheet"><div class="sheet-handle"></div><div class="sheet-head"><div class="title"><b>厨房物品</b><small>点一下切换家里有 / 没有</small></div><button class="icon-close" id="x">×</button></div><div class="manage-tabs"><button data-tab="food" class="${tab==='food'?'on':''}">食材</button><button data-tab="seasoning" class="${tab==='seasoning'?'on':''}">调味料</button><button data-tab="tool" class="${tab==='tool'?'on':''}">厨具</button></div><div class="picker-grid">${names.map(n=>`<button class="pick ${has(tab,n)?'on':''}" data-pick="${tab}|${n}">${icon(n)} ${n}${has(tab,n)?' ✓':''}</button>`).join('')}</div><div class="sheet-footer"><button class="secondary" id="back" style="width:100%">返回冰箱</button></div></div></div>`;q('#x').onclick=close;q('#back').onclick=close;qa('[data-tab]').forEach(b=>b.onclick=()=>manageModal(b.dataset.tab));qa('[data-pick]').forEach(b=>b.onclick=()=>{let[k,n]=b.dataset.pick.split('|');has(k,n)?missing(k,n):have(k,n);manageModal(tab)})}
function shoppingModal(returnId=null){q('#modal').innerHTML=`<div class="modal"><div class="sheet"><div class="sheet-handle"></div><div class="sheet-head"><div class="title"><b>🛍 购物袋</b><small>${returnId?'买到后可直接返回刚才的菜谱。':'买到后会自动记进厨房。'}</small></div><button class="icon-close" id="x">×</button></div>${state.shopping.length?state.shopping.map(x=>`<div class="shopping-row"><div style="font-size:22px">${x.kind==='food'?FOOD[x.name]:x.kind==='seasoning'?'🧂':'🍳'}</div><div class="grow"><b>${x.name}</b><small>${x.kind==='food'?'食材':x.kind==='seasoning'?'调味料':'厨具'}</small></div><button class="tiny" data-bought="${x.kind}|${x.name}">买到了</button><button class="remove" data-rm="${x.kind}|${x.name}">移除</button></div>`).join(''):'<div class="empty">购物袋是空的</div>'}<div class="sheet-footer"><div class="dual"><button class="secondary" id="back">${returnId?'返回菜谱':'关闭'}</button><button class="primary" id="done">完成采购</button></div></div></div></div>`;q('#x').onclick=close;q('#back').onclick=()=>returnId?recipeModal(returnId):close();q('#done').onclick=()=>{close();toast('购物袋已保存')};qa('[data-bought]').forEach(b=>b.onclick=()=>{let[k,n]=b.dataset.bought.split('|');have(k,n);shoppingModal(returnId)});qa('[data-rm]').forEach(b=>b.onclick=()=>{let[k,n]=b.dataset.rm.split('|');rmShop(k,n);save();shoppingModal(returnId)})}
qa('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.s));q('#shoppingBtn').onclick=()=>shoppingModal();save();render();
