// V0.4.7 terminology + flow polish: 菜板 -> 菜谱, focused prep mode.
state.version='0.4.7';

sceneMeta040=function(scene){
  return {
    home:['首页','今天吃什么'],
    fridge:['冰箱','我有什么'],
    board:['菜谱','找菜和选菜'],
    stove:['灶台','今日菜单'],
    mine:['我的','设置']
  }[scene]||['我的小厨房',''];
};

function polishRecipeScene0407(){
  if(state.scene!=='board'||state.meal?.phase==='prep')return;
  const h=q('#root > h2');
  if(h)h.textContent='📖 菜谱';

  const all=q('[data-board-mode="recipes"]');
  const byFood=q('[data-board-mode="ingredients"]');
  if(all)all.textContent='全部菜谱';
  if(byFood)byFood.textContent='按食材找';

  const search=q('#search');
  if(search)search.placeholder='搜索菜名、食材';
  const foodSearch=q('#foodSearch');
  if(foodSearch)foodSearch.placeholder='搜索想用的食材';
}

const boardV0407Base=board;
board=function(){
  const out=boardV0407Base();
  polishRecipeScene0407();
  return out;
};

const stoveV0407Base=stove;
stove=function(){
  stoveV0407Base();

  const pick=q('#stovePickDishes0406');
  if(pick)pick.textContent='去菜谱选菜';

  const prep=q('#menuStartPrep0406');
  if(prep)prep.textContent='开始集中准备';

  qa('.today-summary-0406 small').forEach(el=>{
    if(el.textContent==='分钟合计')el.textContent='时长合计';
  });
};

const setChromeV0407Base=setChrome040;
setChrome040=function(){
  setChromeV0407Base();

  // Preparation is a focused workflow, not a top-level "菜谱" page.
  const focusedPrep=state.meal?.phase==='prep';
  document.body.classList.toggle('focused-prep-0407',focusedPrep);

  const recipeNav=q('.nav button[data-s="board"]');
  if(recipeNav){
    const text=[...recipeNav.childNodes].find(n=>n.nodeType===Node.TEXT_NODE);
    if(text)text.nodeValue='菜谱';
  }
};

// Keep visible labels consistent even where older renderers still emit “菜板”.
const renderV0407Base=render;
render=function(){
  const out=renderV0407Base();
  if(state.scene==='board'&&state.meal?.phase!=='prep')polishRecipeScene0407();
  setChrome040();
  return out;
};

// About text is generated by an earlier patch; refresh it after rendering My.
const mineV0407Base=mine040;
mine040=function(){
  mineV0407Base();
  const aboutTitle=q('.about-040 b');if(aboutTitle)aboutTitle.textContent='我的小厨房 · V0.4.7';
  const about=q('.about-040 p');
  if(about)about.textContent='首页负责推荐，冰箱负责库存，菜谱负责找菜和选菜，灶台负责今日菜单与制作。';
  setChrome040();
};

save();
render();
