import fs from 'node:fs';
import path from 'node:path';

// Generate with the robust markdown/stage parser first.
await import('./sync-hoc-v3.mjs');

const outFile=path.resolve(process.argv[3]||'hoc-recipes.generated.js');
const reportFile=path.resolve('hoc-sync-report.json');
const raw=fs.readFileSync(outFile,'utf8');
const prefix='window.HOC_DATA=';
const at=raw.indexOf(prefix);
if(at<0)throw new Error('Generated HOC_DATA payload not found');
const jsonText=raw.slice(at+prefix.length).trim().replace(/;\s*$/,'');
const data=JSON.parse(jsonText);

const canonicalMap=new Map([
  ['京葱','葱'],['火葱','葱'],['蒜花','蒜'],['青蒜','蒜苗'],
  ['鸡肫','鸡胗'],['鸡胗片','鸡胗'],['瘦肉末','肉末'],
  ['干海带丝','海带丝'],['清水笋丝','笋丝'],['罗汉笋块','罗汉笋']
]);

function definitelySeasoning(name){
  if(/(果汁|椰汁|奶|豆浆|乌龙茶|红茶|绿茶|饮料|可乐|雪碧|芬达|矿泉水)$/.test(name))return false;
  return [
    /^(糖|盐|食用油|淀粉|玉米淀粉|味精|鸡精|胡椒|白胡椒|黑胡椒|花椒|干青花椒|芝麻|白芝麻|孜然)$/,
    /(生抽|老抽|酱油|味极鲜|蚝油|料酒|黄酒|花雕酒|米酒|糯米酒|食用酒精|醋$|陈醋|香醋|米醋)/,
    /(八角|陈皮|山奈|草果|小茴香|桂皮|香叶|十三香|五香粉|椒盐)/,
    /(豆瓣$|豆瓣酱|番茄酱|辣椒酱|甜面酱|黄豆酱|沙茶酱|芝麻酱|花生酱|老干妈)/,
    /(泡椒|剁椒|干红椒|干辣椒|干红辣椒|辣椒段|辣椒面|辣椒粉|辣椒油|红油)/,
    /(蜂蜜|麦芽糖|冰糖|红糖|白糖|白砂糖)/,
    /(调味酱|复合酱|酱汁|酱料|调味汁|风味汁|鸡汁|姜汁|花椒汁|豉油汁|蒸鱼汁|烧肉汁|糖醋汁)$/,
    /(汤料|底料|调味料|调味粉|卤料|香辛料|料包|调料)$/,
    /酱$/,/汁$/,/油$/
  ].some(r=>r.test(name));
}

function canon(name){return canonicalMap.get(name)||name}

for(const r of data.recipes){
  const newIngs=[];
  const newSeason=[];
  const seenFood=new Set();
  const seenSeason=new Set();
  for(const item of r.ings||[]){
    let [name,amount,prep]=item;name=canon(name);
    if(definitelySeasoning(name)){
      if(!seenSeason.has(name)){newSeason.push([name,amount||'适量',1]);seenSeason.add(name)}
    }else if(!seenFood.has(name)){
      newIngs.push([name,amount,prep]);seenFood.add(name);
    }
  }
  for(const item of r.season||[]){
    let [name,amount,required]=item;name=canon(name);
    if(!seenSeason.has(name)){newSeason.push([name,amount,required]);seenSeason.add(name)}
  }
  r.ings=newIngs;
  r.season=newSeason;
}

// Rebuild inventory dictionaries from the final recipe semantics, so no stale
// parser intermediates leak into the fridge/ingredient browser.
const oldFoods=data.foods||{};
const oldGroups=data.foodGroups||{};
const finalFoods={};
const finalGroups={};
const finalSeason=new Set(data.seasonings||[]);
for(const r of data.recipes){
  for(const [name] of r.ings||[]){
    finalFoods[name]=oldFoods[name]||oldFoods[[...canonicalMap.entries()].find(([,v])=>v===name)?.[0]]||'🥣';
    finalGroups[name]=oldGroups[name]||'主食与其他';
  }
  for(const [name] of r.season||[])finalSeason.add(name);
}
for(const name of [...finalSeason]){
  if(definitelySeasoning(name))delete finalFoods[name];
}
data.foods=finalFoods;
data.foodGroups=finalGroups;
data.seasonings=[...finalSeason].filter(Boolean).sort((a,b)=>a.localeCompare(b,'zh-CN'));
data.meta.note='菜名、配料及配方参数依据来源记录整理；普通批量菜谱按比例缩放，多阶段菜谱保留步骤中的分阶段克重；食材/调味料已统一语义。CookLikeHOC 非老乡鸡官方仓库。';

const gongbao=data.recipes.find(r=>r.name==='宫保鸡丁');
const feichang=data.recipes.find(r=>r.name==='肥肠鸡');
const chickenAmount=gongbao?.ings?.find(x=>x[0]==='鸡腿肉')?.[1]||null;
const gongbaoSauce=gongbao?.season?.find(x=>x[0].includes('宫保鸡丁'))?.[1]||null;
if(!gongbao)throw new Error('Smoke check failed: 宫保鸡丁 not found');
if(!feichang?.source?.complex)throw new Error('Smoke check failed: 肥肠鸡 not marked as multi-stage');
if(!feichang.ings.every(x=>x[1]==='见步骤'))throw new Error('Smoke check failed: multi-stage ingredient amounts should be 见步骤');
const chickenNum=parseFloat(chickenAmount);
if(!Number.isFinite(chickenNum)||chickenNum>500)throw new Error(`Smoke check failed: 宫保鸡丁 household chicken amount=${chickenAmount}`);

const report=JSON.parse(fs.readFileSync(reportFile,'utf8'));
report.foodCount=Object.keys(data.foods).length;
report.seasoningCount=data.seasonings.length;
report.overlapCount=Object.keys(data.foods).filter(n=>data.seasonings.includes(n)).length;
report.smoke={gongbaoChicken:chickenAmount,gongbaoSauce,feichangComplex:true,feichangSteps:feichang.steps.length};
if(report.overlapCount)throw new Error(`Food/seasoning overlap remains: ${report.overlapCount}`);

fs.writeFileSync(outFile,`// AUTO-GENERATED by scripts/sync-hoc-v4.mjs. Do not edit manually.\nwindow.HOC_DATA=${JSON.stringify(data,null,2)};\n`,'utf8');
fs.writeFileSync(reportFile,JSON.stringify(report,null,2)+'\n','utf8');
console.log(JSON.stringify(report,null,2));
